version = 5.2.2
archive_dir = /etc/letsencrypt/archive/sonzaiigi.art
cert = /etc/letsencrypt/live/sonzaiigi.art/cert.pem
privkey = /etc/letsencrypt/live/sonzaiigi.art/privkey.pem
chain = /etc/letsencrypt/live/sonzaiigi.art/chain.pem
fullchain = /etc/letsencrypt/live/sonzaiigi.art/fullchain.pem
[renewalparams]
account = 0de9b0ef8efca4b93239dae5970d59f0
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
sonzaiigi.art = /var/www/certbot
